use color4 instead. Because it will cause this issue: Edit/Lyrics/Extends/Components/LabelledObjectFieldTextBox.cs(118,36): error CS0172: Type of conditional expression cannot be determined because 'Color4' and 'SRGBColour' implicitly convert to one another [/home/runner/work/karaoke/karaoke/osu.Game.Rulesets.Karaoke/osu.Game.Rulesets.Karaoke.csproj]